
# main config file 
configfile: "config/config.yml"

# add files from ENCODE4 chromatin experiments to config
configfile: "config/encode4_k562_chrom_data.yml"

# workflow rules
include: "rules/encode_chromatin_abc_models.smk"
include: "rules/make_feature_table.smk"

rule all:
  input:
    expand("results/{file_type}/K562/{abc_type}_abc_models_crispr.tsv.gz",
      file_type = ["bam", "bigWig"], abc_type = ["assayOnly", "assayDHS"]),
    expand("results/bigWig/{cell_type}/EnhAct_features_ABC_egPairs.tsv.gz",
      cell_type = ["K562"]),
    "results/bigWig/K562/EnhActABC_distal_reg_pred_config_bigWig.tsv",
    "results/bam/K562/EnhActABC_distal_reg_pred_config_bam.tsv",
