
# ABC candidate region files
abc_candidate_regions:
  K562: "/oak/stanford/groups/engreitz/Users/atan5133/encode_dataset_processing/results/dhs_only/K562_ENCSR000EOT/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed"
#  GM12878: "/oak/stanford/groups/engreitz/Users/atan5133/encode_dataset_processing/results/dhs_only/GM12878_ENCSR000EMT/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed"
    
# ABC prediction files including Hi-C
abc_predictions:
  K562: "/oak/stanford/groups/engreitz/Users/atan5133/encode_dataset_processing/results/dhs_only/K562_ENCSR000EOT/Predictions/EnhancerPredictionsAllPutative.tsv.gz"
#  GM12878: "/oak/stanford/groups/engreitz/Users/atan5133/encode_dataset_processing/results/dhs_only/GM12878_ENCSR000EMT/Predictions/EnhancerPredictionsAllPutative.tsv.gz"

# TSS annotations
genes: "workflow/ABC-Enhancer-Gene-Prediction/reference/hg38/CollapsedGeneBounds.hg38.TSS500bp.bed"
  
# combined CRISPR data for filtering of gene universe
crispr_data: "/oak/stanford/groups/engreitz/Projects/Benchmarking/CRISPR_data/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz"

# default DNase-seq file accession (same as for K562 ABC)
default_dnase:
  bam: "ENCFF860XAE"
  bigWig: "ENCFF338LXW"

# directory on scratch for faster IO and temporary storage
scratch: "/scratch/users/agschwin"
