
# ABC candidate region files
abc_candidate_regions:
  K562: "/oak/stanford/groups/engreitz/Projects/Benchmarking/Revisions/Predictors/ABC/dnase_h3k27ac_intactHiC/K562/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed"
  GM12878: "/oak/stanford/groups/engreitz/Projects/Benchmarking/Revisions/Predictors/ABC/dnase_h3k27ac_intactHiC/GM12878/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed"
    
# ABC prediction files including Hi-C
abc_predictions:
  K562: "/oak/stanford/groups/engreitz/Projects/Benchmarking/Revisions/Predictors/ABC/dnase_h3k27ac_intactHiC/K562/Predictions/EnhancerPredictionsAllPutative.tsv.gz"
  GM12878: "/oak/stanford/groups/engreitz/Projects/Benchmarking/Revisions/Predictors/ABC/dnase_h3k27ac_intactHiC/GM12878/Predictions/EnhancerPredictionsAllPutative.tsv.gz"

# gene annotations
genes: "workflow/ABC-Enhancer-Gene-Prediction/reference/hg38/CollapsedGeneBounds.hg38.bed"
  
# combined CRISPR data for filtering of ABC predictions
crispr_url: "https://github.com/EngreitzLab/CRISPR_comparison/raw/refs/heads/main/resources/crispr_data/EPCrisprBenchmark_combined_data.training_K562.GRCh38.tsv.gz"
crispr_data: "resources/EPCrisprBenchmark_combined_data.training_K562.GRCh38.tsv.gz"

# distal regulation predictor config file
distal_reg_pred_config: "resources/benchmarking_pred_config.tsv"

# default DNase-seq file accession
default_dnase:
  K562:
    bam: "ENCFF860XAE"
    bigWig: "ENCFF338LXW"
  GM12878:
    bam: "ENCFF940NSD"
    bigWig: "ENCFF960FMM"

# directory on scratch for faster IO and temporary storage
scratch: "/scratch/users/agschwin"
