
# ABC candidate region files
abc_candidate_regions:
  K562: "/oak/stanford/groups/akundaje/kmualim/02212022_hg38Preds_QNORM-hic/K562_ID_2644/Neighborhoods/EnhancerList.txt"
  GM12878: "/oak/stanford/groups/akundaje/kmualim/02212022_hg38Preds_QNORM-hic/GM12878_ID_2724/Neighborhoods/EnhancerList.txt"
    
# ABC prediction files including Hi-C
abc_predictions:
  K562: "/oak/stanford/groups/akundaje/kmualim/02212022_hg38Preds_QNORM-hic/K562_ID_2644/Predictions/EnhancerPredictionsAllPutative.txt.gz"
  GM12878: "/oak/stanford/groups/akundaje/kmualim/02212022_hg38Preds_QNORM-hic/GM12878_ID_2724/Predictions/EnhancerPredictionsAllPutative.txt.gz"
  
# combined CRISPR data for filtering of gene universe
crispr_data: "/oak/stanford/groups/engreitz/Projects/Benchmarking/CRISPR_data/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz"

# default DNase-seq file accession (same as for K562 ABC)
default_dnase:
  bam: "ENCFF860XAE"
  bigWig: "ENCFF338LXW"

# directory on scratch for faster IO and temporary storage
scratch: "/scratch/users/agschwin"
