
# ABC candidate region files
abc_candidate_regions:
  K562: "/oak/stanford/groups/engreitz/Users/atan5133/abc_run_comparisons/current_ABC_results/K562_dhs_h3k27ac_intact_hic/Peaks/macs2_peaks.narrowPeak.sorted.candidateRegions.bed"
#  GM12878: "/oak/stanford/groups/akundaje/kmualim/02212022_hg38Preds_QNORM-hic/GM12878_ID_2724/Neighborhoods/EnhancerList.txt"
    
# ABC prediction files including Hi-C
abc_predictions:
  K562: "/oak/stanford/groups/engreitz/Users/atan5133/abc_run_comparisons/current_ABC_results/K562_dhs_h3k27ac_intact_hic/Predictions/EnhancerPredictionsAllPutative.tsv.gz"
#  GM12878: "/oak/stanford/groups/akundaje/kmualim/02212022_hg38Preds_QNORM-hic/GM12878_ID_2724/Predictions/EnhancerPredictionsAllPutative.txt.gz"

# TSS annotations
genes: "workflow/ABC-Enhancer-Gene-Prediction/reference/hg38/CollapsedGeneBounds.hg38.TSS500bp.bed"
  
# combined CRISPR data for filtering of gene universe
crispr_data: "/oak/stanford/groups/engreitz/Projects/Benchmarking/CRISPR_data/EPCrisprBenchmark_ensemble_data_GRCh38.tsv.gz"

# default DNase-seq file accession (same as for K562 ABC)
default_dnase:
  bam: "ENCFF860XAE"
  bigWig: "ENCFF338LXW"

# directory on scratch for faster IO and temporary storage
scratch: "/scratch/users/agschwin"
